# Thoraric Surgery

In [961]:
import numpy as np
import pandas as pd
    

In [962]:
TS = pd.read_csv('ThoraricSurgery.csv', header=None)
TS

0   1     2     3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
0    293   1  3.80  2.80   0   0   0   0   0   0  12   0   0   0   1   0  62   
1      1   2  2.88  2.16   1   0   0   0   1   1  14   0   0   0   1   0  60   
2      8   2  3.19  2.50   1   0   0   0   1   0  11   0   0   1   1   0  66   
3     14   2  3.98  3.06   2   0   0   0   1   1  14   0   0   0   1   0  80   
4     17   2  2.21  1.88   0   0   1   0   0   0  12   0   0   0   1   0  56   
..   ...  ..   ...   ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..   
465   98   6  3.04  2.40   2   0   0   0   1   0  11   0   0   0   1   0  76   
466  369   6  3.88  2.72   1   0   0   0   1   0  12   0   0   0   1   0  77   
467  406   6  5.36  3.96   1   0   0   0   1   0  12   0   0   0   0   0  62   
468   25   8  4.32  3.20   0   0   0   0   0   0  11   0   0   0   0   0  58   
469  447   8  5.20  4.10   0   0   0   0   0   0  12   0   0   0   0   0  49   

     17  
0     0  
1     0  
2     1  
3     1  
4     0  
..   ..  
465   0  
466   0  
467   0  
468   1  
469   0  

[470 rows x 18 columns]

In [963]:
X = TS.iloc[:,:-1].values
y = TS[17].values

In [964]:
X

array([[293.  ,   1.  ,   3.8 , ...,   1.  ,   0.  ,  62.  ],
       [  1.  ,   2.  ,   2.88, ...,   1.  ,   0.  ,  60.  ],
       [  8.  ,   2.  ,   3.19, ...,   1.  ,   0.  ,  66.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,   0.  ,  62.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,   0.  ,  58.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,   0.  ,  49.  ]])

In [965]:
y

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,

In [966]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=2021, test_size=0.2, stratify=y
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((376, 17), (94, 17), (376,), (94,))

In [967]:
X.shape,y.shape

((470, 17), (470,))

In [968]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=2021)
dtc.fit(X_train,y_train)

DecisionTreeClassifier(random_state=2021)

In [969]:
pred = dtc.predict(X_test)
pred

array([0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0], dtype=int64)

In [970]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.6808510638297872

In [971]:
dtc.score(X_test, y_test)

0.6808510638297872

In [989]:
from sklearn.svm import SVC
svc = SVC(random_state=2021)
svc.fit(X_train, y_train)

SVC(random_state=2021)

In [990]:
pred_sv = svc.predict(X_test)
accuracy_score(y_test, pred_sv)

0.851063829787234

In [972]:
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': 2021,
 'splitter': 'best'}

In [973]:
from sklearn.model_selection import GridSearchCV

In [974]:
params = {
    'max_depth':[2,4,5,6,7],
    'min_samples_split' : [2,3,4,5,6]
}

In [975]:
grid_dt = GridSearchCV(dtc, param_grid=params, scoring='accuracy', cv=3)
grid_dt.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(random_state=2021),
             param_grid={'max_depth': [2, 4, 5, 6, 7],
                         'min_samples_split': [2, 3, 4, 5, 6]},
             scoring='accuracy')

In [976]:
grid_dt.best_params_

{'max_depth': 2, 'min_samples_split': 2}

In [977]:
grid_dt.score(X_test, y_test)

0.8297872340425532

In [978]:
y_test[50],X_test[50]

(0,
 array([203.  ,   2.  ,   4.08,   2.56,   1.  ,   1.  ,   1.  ,   0.  ,
          0.  ,   0.  ,  13.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,
         54.  ]))

In [979]:
grid_dt.predict(X_test[50].reshape(1,-1))   

array([1], dtype=int64)

- accuracy_score, 정밀도, 재현율, F1 스코어 구하기

In [980]:
TS = pd.read_csv('ThoraricSurgery.csv', header=None)
TS

0   1     2     3   4   5   6   7   8   9   10  11  12  13  14  15  16  \
0    293   1  3.80  2.80   0   0   0   0   0   0  12   0   0   0   1   0  62   
1      1   2  2.88  2.16   1   0   0   0   1   1  14   0   0   0   1   0  60   
2      8   2  3.19  2.50   1   0   0   0   1   0  11   0   0   1   1   0  66   
3     14   2  3.98  3.06   2   0   0   0   1   1  14   0   0   0   1   0  80   
4     17   2  2.21  1.88   0   0   1   0   0   0  12   0   0   0   1   0  56   
..   ...  ..   ...   ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..   
465   98   6  3.04  2.40   2   0   0   0   1   0  11   0   0   0   1   0  76   
466  369   6  3.88  2.72   1   0   0   0   1   0  12   0   0   0   1   0  77   
467  406   6  5.36  3.96   1   0   0   0   1   0  12   0   0   0   0   0  62   
468   25   8  4.32  3.20   0   0   0   0   0   0  11   0   0   0   0   0  58   
469  447   8  5.20  4.10   0   0   0   0   0   0  12   0   0   0   0   0  49   

     17  
0     0  
1     0  
2     1  
3     1  
4     0  
..   ..  
465   0  
466   0  
467   0  
468   1  
469   0  

[470 rows x 18 columns]

In [981]:
X = TS.iloc[:,:-1].values
y = TS[17].values

In [982]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[61, 19],
       [11,  3]], dtype=int64)

In [983]:
from sklearn.metrics import precision_score, recall_score

- ##### acurracy_score

In [984]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.6808510638297872

- #### 정밀도

In [985]:
precision_score(y_test, pred)

0.13636363636363635

- #### 재현율

In [986]:
recall_score(y_test, pred)

0.21428571428571427

- #### F1.스코어

In [987]:
2*precision_score(y_test, pred)*recall_score(y_test, pred)/(precision_score(y_test, pred)+recall_score(y_test, pred))

0.16666666666666663

In [988]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test,pred)
print('f1 스코어: {0:0.4f}'.format(f1))

f1 스코어: 0.1667
